name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - name: Run script
      env:
        TWITTER_API_CONSUMER_KEY: ${{ secrets.TWITTER_API_CONSUMER_KEY }}
        TWITTER_API_CONSUMER_SECRET: ${{ secrets.TWITTER_API_CONSUMER_SECRET }}
        TWITTER_API_ACCESS_TOKEN: ${{ secrets.TWITTER_API_ACCESS_TOKEN }}
        TWITTER_API_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_API_ACCESS_TOKEN_SECRET }}
      run: bundle exec ruby app.rb
    - name: Auto commit
      uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        file_pattern: 'data/*.json'
        commit_message: Update data
